FROM golang:1.21 AS build-stage

WORKDIR /app

COPY go.* ./
RUN go mod download

COPY . ./
RUN CGO_ENABLED=0 GOOS=linux go build -o /agent ./cmd/agent

FROM alpine:3.19 AS build-release-stage
WORKDIR /app
COPY --from=build-stage /agent /app/agent
EXPOSE 8080

# Run the binary program produced by `go install`
CMD ["/app/agent"]